version: "2.0"
services:
  # 第1个容器
  jd1:
    image: evinedeng/jd  # 如果要从gitee更新脚本，则为：evinedeng/jd:gitee
    container_name: jd1
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: jd1
    volumes:
      - ./jd1/config:/jd/config
      - ./jd1/log:/jd/log
      #- ./jd1/scripts:/jd/scripts    # 如果想要看到lxk0301大佬的js脚本，以方便的添加额外脚本，可以解除本行注释，下同
    ports:
      - 5678:5678
    environment: 
      - ENABLE_HANGUP=true            # 是否在启动容器时自动启动挂机程序
      - ENABLE_WEB_PANEL=true         # 是否在启动容器时自动启动控制面板

  # 第2个容器
  jd2:
    image: evinedeng/jd # 如果要从gitee更新脚本，则为：evinedeng/jd:gitee
    container_name: jd2
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: jd2
    volumes:
      - ./jd2/config:/jd/config
      - ./jd2/log:/jd/log
    ports:
      - 5679:5678
    environment: 
      - ENABLE_HANGUP=true            # 是否在启动容器时自动启动挂机程序
      - ENABLE_WEB_PANEL=true         # 是否在启动容器时自动启动控制面板

  # 第3个容器，以此类推
  jd3:
    image: evinedeng/jd # 如果要从gitee更新脚本，则为：evinedeng/jd:gitee
    container_name: jd3
    restart: always
    tty: true
    network_mode: "bridge"
    hostname: jd3
    volumes:
      - ./jd3/config:/jd/config
      - ./jd3/log:/jd/log
    ports:
      - 5680:5678
    environment: 
      - ENABLE_HANGUP=true            # 是否在启动容器时自动启动挂机程序
      - ENABLE_WEB_PANEL=true         # 是否在启动容器时自动启动控制面板